version: 2.1

jobs:
  test:
    docker:
      - image: python:3.9 
    steps:
      - checkout  
      - run:
          name: Install modules
          command: pip install -r requirements.txt  
      - run:
          name: Run script
          command: python salaryanalysis.py  
      - run:
          name: Run testing
          command: pytest  

workflows:
  version: 2
  test-and-build:
    jobs:
      - test